ADXL357: ADXL357 Class Reference
ADXL357 Class Reference
A ADXL357 class.
#include <ADXL357.h>
Data Structures
struct scale_t
An scale scture.
Public Member Functions
ADXL357 (bool isASELHigh=false)
bool begin ()
bool setRange (adxl357_range_t range)
adxl357_range_t getRange ()
double getScale ()
void setMode (bool isMeasurmentMode)
uint8_t getAnalogDeviceID ()
uint8_t getDeviceMEMSID ()
uint8_t getDeviceID ()
uint8_t getMaskRevision ()
void writeRegister (const ADXL357_REGISTERS &reg, uint8_t value)
uint8_t readRegister (const ADXL357_REGISTERS &reg)
int32_t read20 (const ADXL357_REGISTERS &reg)
int32_t getX ()
int32_t getY ()
int32_t getZ ()
bool getXYZ (int32_t &x, int32_t &y, int32_t &z)
Get Acceleration on X,Y,Z axis.
Protected Attributes
uint8_t _i2caddr
adxl357_range_t _i2c_speed
adxl357_range_t _int_pol
adxl357_range_t _range
adxl357_power_ctl_t _drdy_off
adxl357_power_ctl_t _temp_off
adxl357_power_ctl_t _standby
Static Private Attributes
static scale_t Scale
An scale_t static member.
Detailed Description
A ADXL357 class.
For ADXL357 Accelerometer in I2C bus;
Definition at line 96 of file ADXL357.h.
Constructor & Destructor Documentation
ADXL357()
ADXL357::ADXL357 (bool isASELHigh = false)
Definition at line 12 of file ADXL357.cpp.
                                :
     _i2c_speed(adxl357_range_t::I2C_HS_High_Speed_Mode),
     _int_pol(adxl357_range_t::INT_POL_LOW),
     _range(adxl357_range_t::Range_10_G),
     _drdy_off(adxl357_power_ctl_t::DRDY_OFF_DEFAULT),
     _temp_off(adxl357_power_ctl_t::TEMP_OFF_Enable),
     _standby(adxl357_power_ctl_t::Standby_Standby)
     {
     if(isASELHigh == false){
         _i2caddr = 0x1D;
     }else{
         _i2caddr = 0x53;
     }
 }
References _i2caddr, DRDY_OFF_DEFAULT, I2C_HS_High_Speed_Mode, INT_POL_LOW, Range_10_G, Standby_Standby, and TEMP_OFF_Enable.
Member Function Documentation
begin()
bool ADXL357::begin ()
Definition at line 29 of file ADXL357.cpp.
                     {
     Wire.begin();
     uint8_t analogDID = getAnalogDeviceID();
     uint8_t memsDID = getDeviceMEMSID();
     uint8_t DID = getDeviceID();
     uint8_t RevID = getMaskRevision();
     Serial.print("analogDID: 0x");
     Serial.println(analogDID, HEX);
     Serial.print("memsDID: 0x");
     Serial.println(memsDID, HEX);
     Serial.print("DID: 0x");
     Serial.println(DID, HEX);
     Serial.print("RevID: 0x");
     Serial.println(RevID, HEX);
     if (analogDID != 0xAD) {
         return false;
     }
     if (memsDID != 0x1D) {
         return false;
     }
     if (DID != 0xED) {
         return false;
     }
     if (RevID != 0x01) {
         return false;
     }
     setRange(_range);
     setMode(true);
     return true;
 }
References _range, getAnalogDeviceID(), getDeviceID(), getDeviceMEMSID(), getMaskRevision(), setMode(), and setRange().
getAnalogDeviceID()
uint8_t ADXL357::getAnalogDeviceID ()
Definition at line 114 of file ADXL357.cpp.
{
     return readRegister(ADXL357_REGISTERS::DEVID_AD);
 }
References DEVID_AD, and readRegister().
Referenced by begin().
getDeviceID()
uint8_t ADXL357::getDeviceID ()
Definition at line 123 of file ADXL357.cpp.
{
     return readRegister(ADXL357_REGISTERS::PARTID);
 }
References PARTID, and readRegister().
Referenced by begin().
getDeviceMEMSID()
uint8_t ADXL357::getDeviceMEMSID ()
Definition at line 119 of file ADXL357.cpp.
{
     return readRegister(ADXL357_REGISTERS::DEVID_MST);
 }
References DEVID_MST, and readRegister().
Referenced by begin().
getMaskRevision()
uint8_t ADXL357::getMaskRevision ()
Definition at line 127 of file ADXL357.cpp.
{
     return readRegister(ADXL357_REGISTERS::REVID);
 }
References readRegister(), and REVID.
Referenced by begin().
getRange()
adxl357_range_t ADXL357::getRange ()
Definition at line 84 of file ADXL357.cpp.
{
     return _range;
 }
References _range.
Referenced by getScale().
getScale()
double ADXL357::getScale ()
Definition at line 88 of file ADXL357.cpp.
{
     switch (this->getRange())
     {
     case adxl357_range_t::Range_40_G:
         return ADXL357::Scale._40G;
     case adxl357_range_t::Range_20_G:
         return ADXL357::Scale._20G;
     case adxl357_range_t::Range_10_G:
         return ADXL357::Scale._10G;
     }
 }
References ADXL357::scale_t::_10G, ADXL357::scale_t::_20G, ADXL357::scale_t::_40G, getRange(), Range_10_G, Range_20_G, Range_40_G, and Scale.
getX()
int32_t ADXL357::getX ()
Definition at line 166 of file ADXL357.cpp.
                       {
     return read20(ADXL357_REGISTERS::XDATA3);
 }
References read20(), and XDATA3.
Referenced by getXYZ().
getXYZ()
bool ADXL357::getXYZ (int32_t & x, int32_t & y, int32_t & z)
Get Acceleration on X,Y,Z axis.
Parameters
x the output of x.
y the output of y.
z the output of z.
Definition at line 178 of file ADXL357.cpp.
{
     x = getX();
     y = getY();
     z = getZ();
     return true;
 }
References getX(), getY(), and getZ().
getY()
int32_t ADXL357::getY ()
Definition at line 170 of file ADXL357.cpp.
                       {
     return read20(ADXL357_REGISTERS::YDATA3);
 }
References read20(), and YDATA3.
Referenced by getXYZ().
getZ()
int32_t ADXL357::getZ ()
Definition at line 174 of file ADXL357.cpp.
                       {
     return read20(ADXL357_REGISTERS::ZDATA3);
 }
References read20(), and ZDATA3.
Referenced by getXYZ().
read20()
int32_t ADXL357::read20 (const ADXL357_REGISTERS & reg)
Definition at line 147 of file ADXL357.cpp.
{
     Wire.beginTransmission(this->_i2caddr);
     Wire.write(static_cast<uint8_t>(reg));
     Wire.endTransmission();
     Wire.requestFrom(this->_i2caddr, uint8_t(3));
     uint8_t data3 = Wire.read();
     uint8_t data2 = Wire.read();
     uint8_t data1 = Wire.read();
     int32_t val = static_cast<int32_t>(data3) << 16;
     val |= (static_cast<int32_t>(data2) << 8);
     val |= (static_cast<int32_t>(data1) & 0xF0);
     val = (val<<8)>>12;
     return static_cast<int32_t>(val);
 }
References _i2caddr.
Referenced by getX(), getY(), and getZ().
readRegister()
uint8_t ADXL357::readRegister (const ADXL357_REGISTERS & reg)
Definition at line 138 of file ADXL357.cpp.
{
     Wire.beginTransmission(this->_i2caddr);
     Wire.write(static_cast<uint8_t>(reg));
     Wire.endTransmission();
     Wire.requestFrom(this->_i2caddr, uint8_t(1));
     uint8_t val = Wire.read();
   return val;
 }
References _i2caddr.
Referenced by getAnalogDeviceID(), getDeviceID(), getDeviceMEMSID(), and getMaskRevision().
setMode()
void ADXL357::setMode (bool isMeasurmentMode)
Definition at line 100 of file ADXL357.cpp.
{
     if(isMeasurmentMode == true){
         _standby = adxl357_power_ctl_t::Standby_Measurement;
     }else{
         _standby = adxl357_power_ctl_t::Standby_Standby;
     }
     writeRegister(ADXL357_REGISTERS::POWER_CTL,
     static_cast<uint8_t>(_drdy_off) |
     static_cast<uint8_t>(_temp_off) |
     static_cast<uint8_t>(_standby));
 }
References _drdy_off, _standby, _temp_off, POWER_CTL, Standby_Measurement, Standby_Standby, and writeRegister().
Referenced by begin().
setRange()
bool ADXL357::setRange (adxl357_range_t range)
Definition at line 69 of file ADXL357.cpp.
{
     if(_standby == adxl357_power_ctl_t::Standby_Measurement){
         return false;
     }
     _range = range;
     writeRegister(ADXL357_REGISTERS::RANGE,
     static_cast<uint8_t>(_i2c_speed) |
     static_cast<uint8_t>(_int_pol) |
     static_cast<uint8_t>(_range));
     return true;
 }
References _i2c_speed, _int_pol, _range, _standby, RANGE, Standby_Measurement, and writeRegister().
Referenced by begin().
writeRegister()
void ADXL357::writeRegister (const ADXL357_REGISTERS & reg, uint8_t value)
Definition at line 131 of file ADXL357.cpp.
{
     Wire.beginTransmission(this->_i2caddr);
     Wire.write(static_cast<uint8_t>(reg));
     Wire.write(value);
     Wire.endTransmission();
 }
References _i2caddr.
Referenced by setMode(), and setRange().
Field Documentation
_drdy_off
adxl357_power_ctl_t ADXL357::_drdy_off protected
Definition at line 153 of file ADXL357.h.
Referenced by setMode().
_i2c_speed
adxl357_range_t ADXL357::_i2c_speed protected
Definition at line 149 of file ADXL357.h.
Referenced by setRange().
_i2caddr
uint8_t ADXL357::_i2caddr protected
Definition at line 147 of file ADXL357.h.
Referenced by ADXL357(), read20(), readRegister(), and writeRegister().
_int_pol
adxl357_range_t ADXL357::_int_pol protected
Definition at line 150 of file ADXL357.h.
Referenced by setRange().
_range
adxl357_range_t ADXL357::_range protected
Definition at line 151 of file ADXL357.h.
Referenced by begin(), getRange(), and setRange().
_standby
adxl357_power_ctl_t ADXL357::_standby protected
Definition at line 155 of file ADXL357.h.
Referenced by setMode(), and setRange().
_temp_off
adxl357_power_ctl_t ADXL357::_temp_off protected
Definition at line 154 of file ADXL357.h.
Referenced by setMode().
Scale
ADXL357::scale_t ADXL357::Scale static private
Initial value:
= {
    ._10G = 19.5e-6,
    ._20G = 39e-6,
    ._40G = 78e-6,
}
An scale_t static member.
Stored scale factors in different ranges.
See also
scale_t
Definition at line 113 of file ADXL357.h.
Referenced by getScale().
The documentation for this class was generated from the following files:
ADXL357.h
ADXL357.cpp